# Generated by Django 6.0.3 on 2026-03-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptecomptable',
            old_name='nom',
            new_name='libelle',
        ),
    ]
