# Generated by Django 6.0.3 on 2026-03-25 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('classe', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cree_par',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('gerant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authentification.comptecomptable')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise'),
        ),
    ]
