# Generated by Django 6.0.3 on 2026-04-18 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_rename_nom_comptecomptable_libelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_client', models.CharField(max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=255)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField()),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('ENVOYE', 'Envoyée'), ('PAYE', 'Payée')], default='ATTENTE', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.client')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.entreprise')),
            ],
        ),
    ]
